### ISSUE TITLE
[Bug]: Device Sync breaks permanently when the server address changes

### ISSUE THREAD

**Issue by Psychotoxical** [Psychotoxical/psysonic#1550]
Device Sync stops working for good once the music server's address changes, and the UI gives no indication why. Reported on Discord by zeroZshadow against 1.53.0-rc.1; the code paths below are unchanged on current `main`.

## Root cause

Device Sync identifies a server by its **address**, not by a stable profile id. `serverIndexKeyFromUrl()` (`src/lib/server/serverBaseUrl.ts:11`) returns the server URL without its scheme, and that string is stored as `serverIndexKey` on every selected source and as `ownerServerIndexKey` inside `psysonic-sync.json` on the device.

When the server moves to a different address, no configured profile matches that key any more — and the lookup does not say so. `resolveServerIdForIndexKey()` (`src/lib/server/serverLookup.ts:21`) returns the unmatched key unchanged, so a dead identifier travels on as if it were a valid server id until an API call fails deep downstream.

## Symptoms

1. **Playlists / Albums / Artists panes are empty.** `useDeviceSyncBrowser` takes the owner from the stored sources and does not fall back to the active server (`hooks/useDeviceSyncBrowser.ts:37`). `apiForServer` then throws `Unknown server: …`, which the loaders swallow (`catch { /* ignore */ }`, lines 70, 81, 92). The browser panel has no error or empty state, so the user sees a blank list next to a perfectly healthy server connection.

2. **Deleting from the device fails with "Failed to fetch tracks from server".** `runDeviceSyncSummaryPrompt` builds `deviceSyncAuth()` unconditionally (`utils/runDeviceSyncExecution.ts:118`), even when every source is marked for deletion and nothing needs to be fetched. The server lookup throws, and the toast mapper reports it under its catch-all key (`utils/deviceSyncErrorToast.ts:6`) — hence a message about fetching tracks during a pure delete. The Rust side is already prepared for this case: a failed fetch is tolerated for sources marked for deletion (`sync/batch/payload.rs:170`); the frontend just never gets that far.

3. **The state cannot heal itself.** Every time the device is attached, the manifest auto-import writes the stale owner key straight back into the store (`hooks/useDeviceSyncDeviceScan.ts:104-111`), so clearing the selection in the app does not help.

4. **"Playlist storage" forgets the chosen layout.** The manifest import calls `applyManifestConfiguration()` with values that default to `self-contained` / `playlist-relative` when the manifest carries no such fields (`store/deviceSyncStore.ts:196-197`), overwriting the user's choice on every attach. This one is independent of the address change and new in 1.53.0-rc.1 — `layoutMode` / `playlistPathMode` were introduced in #1501. The ownership binding in symptoms 1-3 is older and has shipped since 1.51.0.

## Workaround

Delete `psysonic-sync.json` from the target folder, then pick the folder again in the app. With no manifest there is no owner, and the browser falls back to the active server.

## Scope of a fix

- Detect an owner key that resolves to no configured server and surface it, instead of passing it on as a server id.
- Offer a repair path. `DeviceSyncLegacyRecovery` is already this dialog — it only triggers for sources that carry no key at all. On the Rust side, `write_device_manifest_for_migration` can already rewrite an owner and its source keys.
- Do not require server credentials when nothing remains to be fetched.
- Give the browser panel a real empty/error state.
- Only apply a manifest's layout configuration when the manifest actually carries those fields.
